<div align="center">
    <h1>Multimedia Communications - COMUL <br> & <br> Multimedia Systems - SISMUL</h1>
    <h2>Auxiliar Notebook - Pytorch:<br>intro. to automatic differenciation </h2>
    <h4>Degree in Telecommunications and Informatics Engineering <br> & <br> Degree in Electrical And Computer Engineering</h4>
    <h5>
    <img width="500" src="img/logo_20230106.jpg"><br>
    2025 / 26</h5>
</div>

<div align="left">
    <h5>Authors: Luís Vilaça (snv@isep.ipp.pt), Paula Viana (pmv@isep.ipp.pt)</h5>
</div>

---

### Introduction

[PyTorch](https://pytorch.org) become a synonymous of Deep Learning since it provides people with an easy way to work with data, design models, optimize model parameters, and to use the trained models. This nodebook will introduce you to its interface and will focus on the following key points:
1. working with tensors; <br>
2. using GPUs to accelerate operations; <br>
3. working with automatic differentiation; <br>

For additional information, please consult these references:

- Official PyTorch **tutorials** are available at: https://pytorch.org/tutorials/
- Clear and complete **documentation** is at: https://pytorch.org/docs/stable/index.html

There is also an official **forum** where you can ask anything related with PyTorch (about coding, installing, research, etc.) and be sure that someone will eventually answer: https://discuss.pytorch.org/


### 1. The basics of Pytorch

We will start with reviewing the very basic concepts of PyTorch. As a prerequisite, we recommend to be familiar with the **numpy** package as most machine learning frameworks are based on very similar concepts. If you are not familiar with numpy yet, don’t worry: here is a tutorial to go through.

So, let’s start with importing PyTorch. The package is called torch, based on its original framework Torch. As a first step, we can check its version:

In [1]:
import torch
print("Using torch", torch.__version__)

Using torch 2.12.0+cu130


As in every machine learning framework, PyTorch provides functions that are stochastic like generating random numbers. However, a very good practice is to setup your code to be reproducible with the exact same random numbers. This is why we set a seed below.

In [2]:
torch.manual_seed(42) # Setting the seed

#### 1.1. Tensors

Tensors are the PyTorch equivalent to Numpy arrays, with the addition to also have support for GPU acceleration (more on that later). 

The name “tensor” is a generalization of concepts you already know. For instance, a vector is a 1-D tensor, and a matrix a 2-D tensor. When working with neural networks, we will use tensors of various shapes and number of dimensions.

Most common functions you know from numpy can be used on tensors as well. Actually, since numpy arrays are so similar to tensors, we can convert most tensors to numpy arrays (and back) but we don’t need it too often.

In [3]:
import numpy as np
import torch

a_np = np.array([[1., 2.], [3.,4.]])
a_torch = torch.Tensor([[1., 2.], [3.,4.]])

print('This is a NumPy array:\n', a_np, '\n')
print('This is a PyTorch tensor:\n', a_torch , '\n')

This is a NumPy array:
 [[1. 2.]
 [3. 4.]] 

This is a PyTorch tensor:
 tensor([[1., 2.],
        [3., 4.]]) 



The function **torch.Tensor** allocates memory for the desired tensor, but reuses any values that have already been in the memory. To directly assign values to the tensor during initialization, there are many alternatives including:

- torch.zeros: Creates a tensor filled with zeros
- torch.ones: Creates a tensor filled with ones
- torch.rand: Creates a tensor with random values uniformly sampled between 0 and 1
- torch.randn: Creates a tensor with random values sampled from a normal distribution with mean 0 and variance 1
- torch.arange: Creates a tensor containing the values 
- torch.Tensor (input list): Creates a tensor from the list elements you provide

You can obtain the shape of a tensor in the same way as in numpy (x.shape), or using the .size method:

In [4]:
shape = a_torch.shape
print("Shape:", a_torch.shape)

size = a_torch.size()
print("Size:", size)

Shape: torch.Size([2, 2])
Size: torch.Size([2, 2])


#### 1.2. Tensor to Numpy, and Numpy to Tensor

Tensors can be converted to numpy arrays, and numpy arrays back to tensors. To transform a numpy array into a tensor, we can use the function **torch.from_numpy**:

In [5]:
np_arr = np.array([[1, 2], [3, 4]])
tensor = torch.from_numpy(np_arr)

print("Numpy array:", np_arr)
print("PyTorch tensor:", tensor)

Numpy array: [[1 2]
 [3 4]]
PyTorch tensor: tensor([[1, 2],
        [3, 4]])


To transform a PyTorch tensor back to a numpy array, we can use the function **.numpy()** on tensors:

In [6]:
tensor = torch.arange(4)
np_arr = tensor.numpy()

print("PyTorch tensor:", tensor)
print("Numpy array:", np_arr)

PyTorch tensor: tensor([0, 1, 2, 3])
Numpy array: [0 1 2 3]


The conversion of tensors to numpy require the tensor to be on the CPU, and not the GPU (more on GPU support in a later section). In case you have a tensor on GPU, you need to call **.cpu()** on the tensor beforehand. Hence, you get a line like np_arr = **tensor.cpu().numpy()**.

#### 1.3. Operations

Most operations that exist in numpy, also exist in PyTorch. A full list of operations can be found in the PyTorch documentation, but we will review the most important ones here.

Let's do a simple operation with these arrays.

In [7]:
x1 = torch.rand(2, 3)
x2 = torch.rand(2, 3)
y = x1 + x2

print("X1", x1)
print("X2", x2)
print("Y", y)

X1 tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
X2 tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])
Y tensor([[1.1388, 1.7086, 1.3236],
        [1.0925, 1.3250, 1.1945]])


Calling **x1 + x2 creates a new tensor** containing the sum of the two inputs. However, **we can also use in-place operations** that are applied directly on the memory of a tensor. We therefore change the values of x2 without the chance to re-accessing the values of x2 before the operation. An example is shown below:

In [8]:
x1 = torch.rand(2, 3)
x2 = torch.rand(2, 3)
print("X1 (before)", x1)
print("X2 (before)", x2)

# In-place operations are usually marked with a underscore postfix (e.g. “add_” instead of “add”)
x2.add_(x1)
print("X1 (after)", x1)
print("X2 (after)", x2)

X1 (before) tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])
X2 (before) tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317]])
X1 (after) tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])
X2 (after) tensor([[1.1360, 1.1952, 1.0107],
        [0.8708, 1.1824, 1.4056]])


Many NumPy functions have an equivalent in PyTorch (usually with the same name):
    
  * `np.reshape`     <--> `torch.reshape` <br>
  * `np.transpose`   <--> `torch.transpose` <br>
  * `np.concatenate` <--> `torch.cat` <br>
  * `np.nonzero`     <--> `torch.nonzero` <br>
  * `np.sum`         <--> `torch.sum` <br>
  * `np.matmul`      <--> `torch.matmul` <br>
  * ...
      
**NumPy broadcasting is also implemented in PyTorch!** Additionally, the indexing mechanism are also similar to Numpy.

Other commonly used operations include matrix multiplications, which are essential for neural networks. There are multiple ways and functions to perform matrix multiplication, some of which we list below:

- **torch.matmul**: matrix product over two tensors, where the specific behavior depends on the dimensions. If both inputs are matrices (2-dimensional tensors), it performs the standard matrix product. For higher dimensional inputs, the function supports broadcasting (for details see the documentation). Can also be written as a @ b, similar to numpy.
- **torch.mm**: Performs the matrix product over two matrices, but doesn’t support broadcasting (see documentation)
- **torch.bmm**: Performs the matrix product with a support batch dimension.
- **torch.einsum**: Performs matrix multiplications and more (i.e. sums of products) using the Einstein summation convention.

#### 1.4. Working with GPU

A crucial feature of PyTorch is the support of GPUs, short for Graphics Processing Unit. A GPU can perform many thousands of small operations in parallel, making it very well suitable for performing large matrix operations in neural networks. When comparing GPUs to CPUs, we can list the following main differences (credit: Kevin Krewell, 2009)

CPUs and GPUs have both different advantages and disadvantages, which is why many computers contain both components and use them for different tasks. In case you are not familiar with GPUs, you can read up more details in this [NVIDIA blog post](https://blogs.nvidia.com/blog/2009/12/16/whats-the-difference-between-a-cpu-and-a-gpu/) or [here](https://www.intel.com/content/www/us/en/products/docs/processors/what-is-a-gpu.html).

GPUs can accelerate the training of your network up to a factor of which is essential for large neural networks. PyTorch implements a lot of functionality for supporting GPUs (mostly those of NVIDIA due to the libraries CUDA and cuDNN).

Performing operations in GPU with PyTorch is simple, yet a bit annoying. We basically need to specify explicitly when we want a tensor to be saved in GPU memory.

In [9]:
x1 = torch.rand(2, 3).cuda()
x2 = torch.rand(2, 3)

print('This is a tensor stored in GPU memory:\n', x1)

This is a tensor stored in GPU memory:
 tensor([[0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062]], device='cuda:0')


For an operation to run successfully, every tensor must be stored in the same memory (GPU or CPU).

In [11]:
print('This will throw an error:\n', x1 + x2)  
# x1 is in GPU, x2 is in CPU

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [12]:
x2 = x2.cuda()
print('This will produce the desired output:\n', x1 + x2)  # now, both tensors are in GPU

This will produce the desired output:
 tensor([[1.0569, 0.3448, 1.2448],
        [0.7826, 0.8848, 0.8151]], device='cuda:0')


What if I try to store a tensor in GPU and my computer does not have one? This will also throw an **error**.
Fortunately, PyTorch provides a simple way to check if a CUDA capable GPU is available.

In [13]:
print('This computer has CUDA:', torch.cuda.is_available())

This computer has CUDA: True


Thus, if we want to write code that can be run in machines with or without GPU, we should create our tensors following this structure:

In [14]:
x = torch.Tensor([1.])  # define whatever tensor you want
if torch.cuda.is_available():
    x = x.cuda()  # if we have GPU, store the tensor there
    
print(x)

tensor([1.], device='cuda:0')


More conveniently, we can define a global variable `DEVICE` (which can be either GPU or CPU) and store all our tensors there when we create them, using the method `to(DEVICE)`.

By default, all tensors you create are stored on the CPU. We can push a tensor to the GPU by using the function **.to(...)**, or **.cuda()**. However, it is often a good practice to define a device object in your code which points to the GPU if you have one, and otherwise to the CPU. Then, you can write your code with respect to this device object, and it allows you to run the same code on both a CPU-only system, and one with a GPU. Let’s try it below. We can specify the device as follows:

In [15]:
DEVICE = 'cuda:0' if torch.cuda.is_available() else 'cpu'
    
y = torch.Tensor([1.]).to(DEVICE)
print(y)

tensor([1.], device='cuda:0')


Finally, to copy a tensor from GPU to CPU memory and then transform it into an equivalent NumPy array:

In [16]:
a = x1.to('cpu').numpy()

print(a)
print(f"type: {type(a)}")

[[0.10531491 0.26949483 0.35881263]
 [0.19936377 0.54719156 0.00616044]]
type: <class 'numpy.ndarray'>


When generating random numbers, the seed between CPU and GPU is not synchronized. Hence, we need to set the seed on the GPU separately to ensure a reproducible code. Note that due to different GPU architectures, running the same code on different GPUs does not guarantee the same random numbers.

Still, we don’t want that our code gives us a different output every time we run it on the exact same hardware. Hence, we also set the seed on the GPU:

In [17]:
# GPU operations have a separate seed we also want to set
if torch.cuda.is_available():
    torch.cuda.manual_seed(42)
    torch.cuda.manual_seed_all(42)

# Additionally, some operations on a GPU are implemented stochastic for efficiency
# We want to ensure that all operations are deterministic on GPU (if used) for reproducibility
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

##### Bottom line:

PyTorch supports GPU, NumPy does not. Thus, **PyTorch can be used as a numerical computation library with GPU acceleration!**

##### Multiple GPUs:

By default, PyTorch uses a single a GPU. However, it also supports multi-GPU and hybrid GPU + CPU modes, which will not be covered in this tutorial. For more information on this subject, please visit: https://pytorch.org/tutorials/beginner/former_torchies/parallelism_tutorial.html

### 2. Autograd: automatic differentiation: dynamic computation graph and backpropagation

One of the main reasons for using PyTorch in Deep Learning projects is that we can automatically get gradients/derivatives of functions that we define. We will mainly use PyTorch for implementing neural networks, and they are just fancy functions. If we use weight matrices in our function that we want to learn, then those are called the parameters or simply the weights.

If our neural network would output a single scalar value, we would talk about taking the derivative, but you will see that quite often we will have multiple output variables (“values”); in that case we talk about gradients.

The first thing we have to do is to specify which tensors require gradients. By default, when we create a tensor, it does not require gradients.

In [18]:
x = torch.ones((3,))
print(x.requires_grad)

False


We can change this for an existing tensor using the function requires_grad_() (underscore indicating that this is a in-place operation). Alternatively, when creating a tensor, you can pass the argument requires_grad=True to most initializers we have seen above.

In [19]:
x.requires_grad_(True)
print(x.requires_grad)

True


Computing and getting the result of gradients at a given point is extremely easy with PyTorch.

E.g.: Consider the following function.

\begin{align}
y = \sum_i(x_i + 2)^2 + 3
\end{align}

If we want to optimize $x$ (either maximize or minimize) the output, we do this through the use of the gradient. Therefore, we want to obtain the values of $x$ that allow $\frac{\partial y}{\partial x} = 0$. Consider $x = [0, 1, 2]$ as your input.

In [20]:
x = torch.Tensor([0., 1., 2.]).float() # Only float tensors can have gradients
x.requires_grad_(True)
print("X", x)

X tensor([0., 1., 2.], requires_grad=True)


Now let’s build the computation graph (**"sequence of operations"**) step by step. You can combine multiple operations in a single line, but we will separate them here to get a better understanding of how each operation is added to the computation graph.

In [21]:
a = x + 2
b = a ** 2
c = b + 3
y = c.sum()
print("Y", y)

Y tensor(38., grad_fn=<SumBackward0>)


Each node of the computation graph has automatically defined a function for calculating the gradients with respect to its inputs, **grad_fn**. You can see this when we printed the output tensor. 

This is why the computation graph is usually visualized in the reverse direction (arrows point from the result to the inputs). We can perform backpropagation on the computation graph by calling the function **backward()** on the last output, which effectively **calculates the gradients for each tensor that has the property requires_grad=True**:

In [22]:
y.backward()
print(x.grad)

tensor([4., 6., 8.])


We'll check that these gradients coincide with the ones computed using their analytical expressions:

$$
\frac{\partial y}{\partial x} = \sum_{i} 2(x+2)
$$

Hence, with the input being $x = [0, 1, 2]$, our gradients are $\frac{\partial y}{\partial x} = [4,6,8]$. The previous code cell should have printed the same result.

Computing higher order derivatives with PyTorch is also possible and it is fairly easy too. However, we will skip it in this presentation. More info: https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html?highlight=gradients

### References (development of this lab script)

This lab script was inspired from the tutorials/documentation from:

[a] Scripts from workshops presented in previous editions of the [CTM OpenDay at INESC TEC](https://opendayctm.inesctec.pt/)

[b] Deep Learning using Pytorch by [Andry Maykol Pinto](amgp@fe.up.pt) (Department of Electrical and Computer Engineering, FEUP)

[c] [CITS4012 Natural Language Processing, Department of Computer Science and Software Engineering at the University of Western Australia.](https://weiliu2k.github.io/CITS4012/index.html)

[d] [UvA Deep Learning Tutorials - Tutorial 2: Introduction to PyTorch](https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/tutorial2/Introduction_to_PyTorch.html)